<tr>
	<td class="row1 row-center" colspan="4">
	<a href="http://www.blinklist.com/index.php?Action=Blink/addblink.php&amp;Description=&amp;Url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_blinklist.png" alt="blinkslist.com" title="blinkslist.com" border="0" /></a>
	<a href="http://blogmarks.net/my/new.php?mini=1&amp;simple=1&amp;url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_blogmarks.png" alt="blogmarks.net" title="blogmarks.net" border="0" /></a>
	<a href="http://co.mments.com/track?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_comments.png" alt="co.mments.com" title="co.mments.com" border="0" /></a>
	<a href="http://del.icio.us/post?v=4&amp;noui&amp;jump=close&amp;url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_delicious.png" alt="del.icio.us" title="del.icio.us" border="0" /></a>
	<a href="http://digg.com/submit?phase=2&amp;url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_digg.png" alt="digg.com" title="digg.com" border="0" /></a>
	<a href="http://www.newsvine.com/_tools/seed&amp;save?u={TOPIC_URL_ENC}&amp;T={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_newsvine.png" alt="newsvine.com" title="newsvine.com" border="0" /></a>
	<a href="http://www.facebook.com/share.php?u={TOPIC_URL_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_facebook.png" alt="facebook.com" title="facebook.com" border="0" /></a>
	<a href="http://cgi.fark.com/cgi/fark/edit.pl?new_url={TOPIC_URL_ENC}&amp;new_comment={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_fark.png" alt="fark.com" title="fark.com" border="0" /></a>
	<a href="http://feedmelinks.com/categorize?from=toolbar&amp;op=submit&amp;url={TOPIC_URL_ENC}&amp;name={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_feedmelinks.png" alt="feedmelinks.com" title="feedmelinks.com" border="0" /></a>
	<a href="http://www.furl.net/storeIt.jsp?t={TOPIC_TITLE_ENC}&amp;u={TOPIC_URL_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_furl.png" alt="furl.net" title="furl.net" border="0" /></a>
	<a href="http://www.google.com/bookmarks/mark?op=edit&amp;output=popup&amp;bkmk={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_google.png" alt="google.com" title="google.com" border="0" /></a>
	<a href="http://www.linkagogo.com/go/AddNoPopup?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_linkagogo.png" alt="linkagogo.com" title="linkagogo.com" border="0" /></a>
	<a href="http://ma.gnolia.com/bookmarklet/snap/add?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_magnolia.png" alt="ma.gnolia.com" title="ma.gnolia.com" border="0" /></a>
	<a href="http://meneame.net/login.php?return=/submit.php?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_meneame.png" alt="meneame.net" title="meneame.net" border="0" /></a>
	<a href="http://www.netscape.com/submit/?U={TOPIC_URL_ENC}&amp;T={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_netscape.png" alt="netscape.com" title="netscape.com" border="0" /></a>
	<a href="http://reddit.com/submit?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_reddit.png" alt="reddit.com" title="reddit.com" border="0" /></a>
	<a href="http://www.shadows.com/features/tcr.htm?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_shadows.png" alt="shadows.com" title="shadows.com" border="0" /></a>
	<a href="http://www.simpy.com/simpy/LinkAdd.do?href={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_simpy.png" alt="simpy.com" title="simpy.com" border="0" /></a>
	<a href="http://slashdot.org/bookmark.pl?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_slashdot.png" alt="slashdot.org" title="slashdot.org" border="0" /></a>
	<a href="http://smarking.com/editbookmark/?url={TOPIC_URL_ENC}&amp;description={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_smarking.png" alt="smarking.com" title="smarking.com" border="0" /></a>
	<a href="http://www.spurl.net/spurl.php?v=3&amp;title={TOPIC_TITLE_ENC}&amp;url={TOPIC_URL_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_spurl.png" alt="spurl.net" title="spurl.net" border="0" /></a>
	<a href="http://www.stumbleupon.com/submit?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_stumbleupon.png" alt="stumbleupon.com" title="stumbleupon.com" border="0" /></a>
	<a href="http://www.technorati.com/faves?add={TOPIC_URL_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_technorati.png" alt="technorati.com" title="technorati.com" border="0" /></a>
	<a href="https://favorites.live.com/quickadd.aspx?marklet=1&amp;mkt=en-us&amp;url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_windowslive.png" alt="favorites.live.com" title="favorites.live.com" border="0" /></a>
	<a href="http://myweb2.search.yahoo.com/myresults/bookmarklet?u={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_yahoomyweb.png" alt="yahoo.com" title="yahoo.com" border="0" /></a>
	<a href="http://www.diggita.it/submit.php?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_diggita.png" alt="DIGG ITA" title="DIGG ITA" border="0" /></a>
	<a href="http://fai.informazione.it/submit.aspx?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_fai.png" alt="Fai Informazione" title="Fai Informazione" border="0" /></a>
	<a href="http://kipapa.it/add.php?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_kipapa.png" alt="KiPapa" title="KiPapa" border="0" /></a>
	<a href="http://oknotizie.alice.it/post?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_okno.png" alt="Ok Notizie" title="Ok Notizie" border="0" /></a>
	<a href="http://segnalo.com/post.html.php?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_segnalo.png" alt="Segnalo" title="Segnalo" border="0" /></a>
	<a href="http://www.bookmark.it/bookmark.php?url={TOPIC_URL_ENC}&amp;title={TOPIC_TITLE_ENC}" target="_blank"><img src="{FULL_SITE_PATH}images/social_bm/sb_bookmarkit.png" alt="Bookmark IT" title="Bookmark IT" border="0" /></a>
	</td>
</tr>
<tr><td class="spaceRow" colspan="4"><img src="{SPACER}" width="1" height="3" alt="" /></td></tr>