<?php
/**
*
* @package Icy Phoenix
* @version $Id$
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
*
* @Extra credits for this file
* Ptirhiik (admin@rpgnet-fr.com)
*
*/

/**
*
* LAST UPDATE 2009-02-18 13:07:44 (GMT) by Mighty Gorgon*
*/

if (!defined('IN_ICYPHOENIX'))
{
	die('Hacking attempt');
	exit;
}

//--------------------------------------------------------------------------------------------------
//
// $tree : designed to get all the hierarchy
// ------
//
//	indexes :
//		- id : full designation : ie Root, f3, c20
//		- idx : rank order
//
//	$tree['keys'][id]			=> idx,
//	$tree['type'][idx]			=> type of the row, can be 'c' for categories or 'f' for forums,
//	$tree['id'][idx]			=> value of the row id : cat_id for cats, forum_id for forums,
//	$tree['data'][idx]			=> db table row,
//	$tree['main'][idx]			=> parent id,
//	$tree['sub'][id]			=> array of sub-level ids,
//--------------------------------------------------------------------------------------------------

$tree = array(
	'keys'	=> array('c1' => 0, 'f1' => 1, 'f2' => 2, 'f3' => 3, 'f4' => 4, 'f7' => 5, 'c4' => 6, 'f8' => 7, 'c2' => 8, 'f5' => 9, 'c3' => 10, 'f6' => 11),
	'type'	=> array('c', 'f', 'f', 'f', 'f', 'f', 'c', 'f', 'c', 'f', 'c', 'f'),
	'id'	=> array('1', '1', '2', '3', '4', '7', '4', '8', '2', '5', '3', '6'),
	'data'	=> array(
				array(
						'cat_id'	=> '1',
						'cat_main'	=> '0',
						'cat_main_type'	=> 'c',
						'cat_title'	=> 'Test category 1',
						'cat_desc'	=> '',
						'icon'	=> '',
						'cat_order'	=> '10',
						'main'	=> 'Root',
					),
				array(
						'forum_id'	=> '1',
						'cat_id'	=> '1',
						'main_type'	=> 'c',
						'forum_name'	=> 'Test Forum 1',
						'forum_desc'	=> '<span class="topic_ann">This is just a test forum.</span>',
						'forum_status'	=> '0',
						'forum_order'	=> '20',
						'forum_posts'	=> '189',
						'forum_topics'	=> '120',
						'forum_last_post_id'	=> '224',
						'forum_postcount'	=> '1',
						'forum_thanks'	=> '1',
						'forum_notify'	=> '1',
						'forum_similar_topics'	=> '1',
						'forum_topic_views'	=> '1',
						'forum_tags'	=> '0',
						'forum_sort_box'	=> '1',
						'forum_kb_mode'	=> '0',
						'forum_index_icons'	=> '1',
						'forum_rules'	=> '1',
						'forum_link'	=> '',
						'forum_link_internal'	=> '0',
						'forum_link_hit_count'	=> '0',
						'forum_link_hit'	=> '0',
						'icon'	=> '',
						'prune_next'	=> '',
						'prune_enable'	=> '0',
						'auth_view'	=> '0',
						'auth_read'	=> '0',
						'auth_post'	=> '0',
						'auth_reply'	=> '0',
						'auth_edit'	=> '1',
						'auth_delete'	=> '3',
						'auth_sticky'	=> '3',
						'auth_announce'	=> '5',
						'auth_globalannounce'	=> '5',
						'auth_news'	=> '5',
						'auth_cal'	=> '5',
						'auth_vote'	=> '1',
						'auth_pollcreate'	=> '1',
						'auth_attachments'	=> '1',
						'auth_download'	=> '1',
						'auth_ban'	=> '3',
						'auth_greencard'	=> '5',
						'auth_bluecard'	=> '1',
						'auth_rate'	=> '-1',
						'main'	=> 'c1',
					),
				array(
						'forum_id'	=> '2',
						'cat_id'	=> '1',
						'main_type'	=> 'c',
						'forum_name'	=> 'Another One',
						'forum_desc'	=> 'Another One',
						'forum_status'	=> '0',
						'forum_order'	=> '30',
						'forum_posts'	=> '11',
						'forum_topics'	=> '5',
						'forum_last_post_id'	=> '105',
						'forum_postcount'	=> '1',
						'forum_thanks'	=> '1',
						'forum_notify'	=> '1',
						'forum_similar_topics'	=> '0',
						'forum_topic_views'	=> '1',
						'forum_tags'	=> '0',
						'forum_sort_box'	=> '0',
						'forum_kb_mode'	=> '0',
						'forum_index_icons'	=> '0',
						'forum_rules'	=> '1',
						'forum_link'	=> '',
						'forum_link_internal'	=> '0',
						'forum_link_hit_count'	=> '0',
						'forum_link_hit'	=> '0',
						'icon'	=> 'images/forums/48_leaf_orange.png',
						'prune_next'	=> '',
						'prune_enable'	=> '0',
						'auth_view'	=> '0',
						'auth_read'	=> '1',
						'auth_post'	=> '1',
						'auth_reply'	=> '1',
						'auth_edit'	=> '1',
						'auth_delete'	=> '1',
						'auth_sticky'	=> '3',
						'auth_announce'	=> '3',
						'auth_globalannounce'	=> '3',
						'auth_news'	=> '2',
						'auth_cal'	=> '0',
						'auth_vote'	=> '1',
						'auth_pollcreate'	=> '1',
						'auth_attachments'	=> '1',
						'auth_download'	=> '0',
						'auth_ban'	=> '3',
						'auth_greencard'	=> '5',
						'auth_bluecard'	=> '1',
						'auth_rate'	=> '-1',
						'main'	=> 'c1',
					),
				array(
						'forum_id'	=> '3',
						'cat_id'	=> '2',
						'main_type'	=> 'f',
						'forum_name'	=> 'Forum Test',
						'forum_desc'	=> 'Forum Test',
						'forum_status'	=> '0',
						'forum_order'	=> '40',
						'forum_posts'	=> '2',
						'forum_topics'	=> '2',
						'forum_last_post_id'	=> '106',
						'forum_postcount'	=> '1',
						'forum_thanks'	=> '1',
						'forum_notify'	=> '0',
						'forum_similar_topics'	=> '0',
						'forum_topic_views'	=> '1',
						'forum_tags'	=> '0',
						'forum_sort_box'	=> '0',
						'forum_kb_mode'	=> '0',
						'forum_index_icons'	=> '0',
						'forum_rules'	=> '0',
						'forum_link'	=> '',
						'forum_link_internal'	=> '0',
						'forum_link_hit_count'	=> '0',
						'forum_link_hit'	=> '0',
						'icon'	=> 'images/forums/48_icy_phoenix.png',
						'prune_next'	=> '',
						'prune_enable'	=> '0',
						'auth_view'	=> '2',
						'auth_read'	=> '1',
						'auth_post'	=> '1',
						'auth_reply'	=> '1',
						'auth_edit'	=> '1',
						'auth_delete'	=> '3',
						'auth_sticky'	=> '1',
						'auth_announce'	=> '3',
						'auth_globalannounce'	=> '5',
						'auth_news'	=> '3',
						'auth_cal'	=> '1',
						'auth_vote'	=> '1',
						'auth_pollcreate'	=> '1',
						'auth_attachments'	=> '0',
						'auth_download'	=> '0',
						'auth_ban'	=> '3',
						'auth_greencard'	=> '5',
						'auth_bluecard'	=> '1',
						'auth_rate'	=> '1',
						'main'	=> 'f2',
					),
				array(
						'forum_id'	=> '4',
						'cat_id'	=> '3',
						'main_type'	=> 'f',
						'forum_name'	=> 'Forum One',
						'forum_desc'	=> 'Forum One',
						'forum_status'	=> '0',
						'forum_order'	=> '50',
						'forum_posts'	=> '5',
						'forum_topics'	=> '4',
						'forum_last_post_id'	=> '107',
						'forum_postcount'	=> '1',
						'forum_thanks'	=> '0',
						'forum_notify'	=> '0',
						'forum_similar_topics'	=> '0',
						'forum_topic_views'	=> '1',
						'forum_tags'	=> '0',
						'forum_sort_box'	=> '0',
						'forum_kb_mode'	=> '0',
						'forum_index_icons'	=> '0',
						'forum_rules'	=> '0',
						'forum_link'	=> '',
						'forum_link_internal'	=> '0',
						'forum_link_hit_count'	=> '0',
						'forum_link_hit'	=> '0',
						'icon'	=> 'images/forums/48_leaf_orange.png',
						'prune_next'	=> '',
						'prune_enable'	=> '0',
						'auth_view'	=> '2',
						'auth_read'	=> '1',
						'auth_post'	=> '1',
						'auth_reply'	=> '1',
						'auth_edit'	=> '1',
						'auth_delete'	=> '3',
						'auth_sticky'	=> '1',
						'auth_announce'	=> '3',
						'auth_globalannounce'	=> '5',
						'auth_news'	=> '3',
						'auth_cal'	=> '1',
						'auth_vote'	=> '1',
						'auth_pollcreate'	=> '1',
						'auth_attachments'	=> '0',
						'auth_download'	=> '0',
						'auth_ban'	=> '3',
						'auth_greencard'	=> '5',
						'auth_bluecard'	=> '1',
						'auth_rate'	=> '1',
						'main'	=> 'f3',
					),
				array(
						'forum_id'	=> '7',
						'cat_id'	=> '1',
						'main_type'	=> 'c',
						'forum_name'	=> 'Forum Self',
						'forum_desc'	=> 'Forum Self',
						'forum_status'	=> '0',
						'forum_order'	=> '60',
						'forum_posts'	=> '9',
						'forum_topics'	=> '8',
						'forum_last_post_id'	=> '127',
						'forum_postcount'	=> '1',
						'forum_thanks'	=> '1',
						'forum_notify'	=> '1',
						'forum_similar_topics'	=> '0',
						'forum_topic_views'	=> '1',
						'forum_tags'	=> '0',
						'forum_sort_box'	=> '0',
						'forum_kb_mode'	=> '0',
						'forum_index_icons'	=> '0',
						'forum_rules'	=> '0',
						'forum_link'	=> '',
						'forum_link_internal'	=> '0',
						'forum_link_hit_count'	=> '0',
						'forum_link_hit'	=> '0',
						'icon'	=> 'images/forums/48_icy_phoenix.png',
						'prune_next'	=> '',
						'prune_enable'	=> '0',
						'auth_view'	=> '0',
						'auth_read'	=> '9',
						'auth_post'	=> '1',
						'auth_reply'	=> '9',
						'auth_edit'	=> '1',
						'auth_delete'	=> '3',
						'auth_sticky'	=> '3',
						'auth_announce'	=> '5',
						'auth_globalannounce'	=> '5',
						'auth_news'	=> '5',
						'auth_cal'	=> '5',
						'auth_vote'	=> '5',
						'auth_pollcreate'	=> '5',
						'auth_attachments'	=> '1',
						'auth_download'	=> '1',
						'auth_ban'	=> '3',
						'auth_greencard'	=> '5',
						'auth_bluecard'	=> '1',
						'auth_rate'	=> '-1',
						'main'	=> 'c1',
					),
				array(
						'cat_id'	=> '4',
						'cat_main'	=> '1',
						'cat_main_type'	=> 'c',
						'cat_title'	=> 'Test Sub Category',
						'cat_desc'	=> 'Test Sub Category',
						'icon'	=> '',
						'cat_order'	=> '70',
						'main'	=> 'c1',
					),
				array(
						'forum_id'	=> '8',
						'cat_id'	=> '4',
						'main_type'	=> 'c',
						'forum_name'	=> 'Test SC SF',
						'forum_desc'	=> 'Test SC SF',
						'forum_status'	=> '0',
						'forum_order'	=> '80',
						'forum_posts'	=> '0',
						'forum_topics'	=> '0',
						'forum_last_post_id'	=> '0',
						'forum_postcount'	=> '1',
						'forum_thanks'	=> '1',
						'forum_notify'	=> '1',
						'forum_similar_topics'	=> '0',
						'forum_topic_views'	=> '1',
						'forum_tags'	=> '0',
						'forum_sort_box'	=> '0',
						'forum_kb_mode'	=> '0',
						'forum_index_icons'	=> '0',
						'forum_rules'	=> '0',
						'forum_link'	=> '',
						'forum_link_internal'	=> '0',
						'forum_link_hit_count'	=> '0',
						'forum_link_hit'	=> '0',
						'icon'	=> '',
						'prune_next'	=> '',
						'prune_enable'	=> '0',
						'auth_view'	=> '0',
						'auth_read'	=> '0',
						'auth_post'	=> '1',
						'auth_reply'	=> '1',
						'auth_edit'	=> '1',
						'auth_delete'	=> '3',
						'auth_sticky'	=> '3',
						'auth_announce'	=> '5',
						'auth_globalannounce'	=> '5',
						'auth_news'	=> '5',
						'auth_cal'	=> '5',
						'auth_vote'	=> '1',
						'auth_pollcreate'	=> '1',
						'auth_attachments'	=> '1',
						'auth_download'	=> '1',
						'auth_ban'	=> '3',
						'auth_greencard'	=> '5',
						'auth_bluecard'	=> '1',
						'auth_rate'	=> '-1',
						'main'	=> 'c4',
					),
				array(
						'cat_id'	=> '2',
						'cat_main'	=> '0',
						'cat_main_type'	=> 'c',
						'cat_title'	=> 'CollapseMe',
						'cat_desc'	=> 'CollapseMe',
						'icon'	=> '',
						'cat_order'	=> '90',
						'main'	=> 'Root',
					),
				array(
						'forum_id'	=> '5',
						'cat_id'	=> '2',
						'main_type'	=> 'c',
						'forum_name'	=> 'Forum Test &amp; Special Chars',
						'forum_desc'	=> 'Forum Test &amp; Special Chars &quot;&quot;',
						'forum_status'	=> '1',
						'forum_order'	=> '100',
						'forum_posts'	=> '7',
						'forum_topics'	=> '5',
						'forum_last_post_id'	=> '108',
						'forum_postcount'	=> '1',
						'forum_thanks'	=> '1',
						'forum_notify'	=> '1',
						'forum_similar_topics'	=> '0',
						'forum_topic_views'	=> '1',
						'forum_tags'	=> '0',
						'forum_sort_box'	=> '0',
						'forum_kb_mode'	=> '0',
						'forum_index_icons'	=> '0',
						'forum_rules'	=> '0',
						'forum_link'	=> '',
						'forum_link_internal'	=> '0',
						'forum_link_hit_count'	=> '0',
						'forum_link_hit'	=> '0',
						'icon'	=> '',
						'prune_next'	=> '',
						'prune_enable'	=> '0',
						'auth_view'	=> '0',
						'auth_read'	=> '0',
						'auth_post'	=> '1',
						'auth_reply'	=> '1',
						'auth_edit'	=> '1',
						'auth_delete'	=> '1',
						'auth_sticky'	=> '3',
						'auth_announce'	=> '3',
						'auth_globalannounce'	=> '3',
						'auth_news'	=> '2',
						'auth_cal'	=> '0',
						'auth_vote'	=> '1',
						'auth_pollcreate'	=> '1',
						'auth_attachments'	=> '1',
						'auth_download'	=> '0',
						'auth_ban'	=> '3',
						'auth_greencard'	=> '5',
						'auth_bluecard'	=> '1',
						'auth_rate'	=> '-1',
						'main'	=> 'c2',
					),
				array(
						'cat_id'	=> '3',
						'cat_main'	=> '0',
						'cat_main_type'	=> 'c',
						'cat_title'	=> 'Reporting',
						'cat_desc'	=> 'Reporting',
						'icon'	=> '',
						'cat_order'	=> '110',
						'main'	=> 'Root',
					),
				array(
						'forum_id'	=> '6',
						'cat_id'	=> '3',
						'main_type'	=> 'c',
						'forum_name'	=> '<span class="topic_ann">Reporting</span>',
						'forum_desc'	=> 'Reporting',
						'forum_status'	=> '0',
						'forum_order'	=> '120',
						'forum_posts'	=> '1',
						'forum_topics'	=> '1',
						'forum_last_post_id'	=> '67',
						'forum_postcount'	=> '1',
						'forum_thanks'	=> '1',
						'forum_notify'	=> '1',
						'forum_similar_topics'	=> '0',
						'forum_topic_views'	=> '1',
						'forum_tags'	=> '0',
						'forum_sort_box'	=> '0',
						'forum_kb_mode'	=> '0',
						'forum_index_icons'	=> '0',
						'forum_rules'	=> '0',
						'forum_link'	=> '',
						'forum_link_internal'	=> '0',
						'forum_link_hit_count'	=> '0',
						'forum_link_hit'	=> '0',
						'icon'	=> '',
						'prune_next'	=> '',
						'prune_enable'	=> '0',
						'auth_view'	=> '5',
						'auth_read'	=> '5',
						'auth_post'	=> '1',
						'auth_reply'	=> '1',
						'auth_edit'	=> '1',
						'auth_delete'	=> '1',
						'auth_sticky'	=> '3',
						'auth_announce'	=> '3',
						'auth_globalannounce'	=> '3',
						'auth_news'	=> '2',
						'auth_cal'	=> '0',
						'auth_vote'	=> '1',
						'auth_pollcreate'	=> '1',
						'auth_attachments'	=> '1',
						'auth_download'	=> '1',
						'auth_ban'	=> '3',
						'auth_greencard'	=> '5',
						'auth_bluecard'	=> '1',
						'auth_rate'	=> '-1',
						'main'	=> 'c3',
					),
			),
	'main'	=> array('Root', 'c1', 'c1', 'f2', 'f3', 'c1', 'c1', 'c4', 'Root', 'c2', 'Root', 'c3'),
	'sub'	=> array(
				'Root'	=> array('c1', 'c2', 'c3'),
				'c1'	=> array('f1', 'f2', 'f7', 'c4'),
				'f2'	=> array('f3'),
				'f3'	=> array('f4'),
				'c4'	=> array('f8'),
				'c2'	=> array('f5'),
				'c3'	=> array('f6'),
			),
	'mods'	=> array(
				1 => array(
			'user_id'			=> array(2, 3),
			'username'		=> array('Mighty Gorgon', 'Solmyr'),
			'user_active'	=> array(1, 1),
			'user_color'	=> array('#ff5500', '#ffdd33'),
			'group_id'		=> array(),
			'group_name'	=> array(),
			'group_color'	=> array(),
		),
				2 => array(
			'user_id'			=> array(2),
			'username'		=> array('Mighty Gorgon'),
			'user_active'	=> array(1),
			'user_color'	=> array('#ff5500'),
			'group_id'		=> array(),
			'group_name'	=> array(),
			'group_color'	=> array(),
		),
				3 => array(
			'user_id'			=> array(2),
			'username'		=> array('Mighty Gorgon'),
			'user_active'	=> array(1),
			'user_color'	=> array('#ff5500'),
			'group_id'		=> array(),
			'group_name'	=> array(),
			'group_color'	=> array(),
		),
				4 => array(
			'user_id'			=> array(2),
			'username'		=> array('Mighty Gorgon'),
			'user_active'	=> array(1),
			'user_color'	=> array('#ff5500'),
			'group_id'		=> array(),
			'group_name'	=> array(),
			'group_color'	=> array(),
		),
				9 => array(
			'user_id'			=> array(2),
			'username'		=> array('Mighty Gorgon'),
			'user_active'	=> array(1),
			'user_color'	=> array('#ff5500'),
			'group_id'		=> array(6),
			'group_name'	=> array('Test'),
			'group_color'	=> array('#ffdd33'),
		),
				5 => array(
			'user_id'			=> array(3),
			'username'		=> array('Solmyr'),
			'user_active'	=> array(1),
			'user_color'	=> array('#ffdd33'),
			'group_id'		=> array(),
			'group_name'	=> array(),
			'group_color'	=> array(),
		),
				11 => array(
			'user_id'			=> array(),
			'username'		=> array(),
			'user_active'	=> array(),
			'user_color'	=> array(),
			'group_id'		=> array(6),
			'group_name'	=> array('Test'),
			'group_color'	=> array('#ffdd33'),
		),
			),
);
return;
?>