<script type="text/javascript">
// <![CDATA[

var cmsEditorLang = {
	'errorWrongBlocksLocation'          : '{L_AJAX_ERROR_WRONG_BLOCKS_LOCATION}',
	'blockTitle'                        : '{L_AJAX_BLOCK_TITLE}',
	'optionEnabled'                     : '{L_AJAX_OPTION_ENABLED}',
	'optionBorder'                      : '{L_AJAX_OPTION_BORDER}',
	'optionTitle'                       : '{L_AJAX_OPTION_TITLE}',
	'optionLocal'                       : '{L_AJAX_OPTION_LOCAL}',
	'optionBackground'                  : '{L_AJAX_OPTION_BACKGROUND}',
	'optionEnabledExplain'              : '{L_AJAX_OPTION_ENABLED_EXPLAIN}',
	'optionBorderExplain'               : '{L_AJAX_OPTION_BORDER_EXPLAIN}',
	'optionTitleExplain'                : '{L_AJAX_OPTION_TITLE_EXPLAIN}',
	'optionLocalExplain'                : '{L_AJAX_OPTION_LOCAL_EXPLAIN}',
	'optionBackgroundExplain'           : '{L_AJAX_OPTION_BACKGROUND_EXPLAIN}',
	'tipTitle'                          : '{L_AJAX_TIP_TITLE}',
	'tipMove'                           : '{L_AJAX_TIP_MOVE}',
	'tipMoveAll'                        : '{L_AJAX_TIP_MOVE_ALL}',
	'tipDelete'                         : '{L_AJAX_TIP_DELETE}',
	'tipAdd'                            : '{L_AJAX_TIP_ADD}',
	'tipChangeType'                     : '{L_AJAX_TIP_CHANGE_TYPE}',
	'tipChangeView'                     : '{L_AJAX_TIP_CHANGE_VIEW}',
	'buttonChange'                      : '{L_AJAX_BUTTON_CHANGE}',
	'buttonCancel'                      : '{L_AJAX_BUTTON_CANCEL}',
	'buttonRestore'                     : '{L_AJAX_BUTTON_RESTORE}',
	'buttonAdd'                         : '{L_AJAX_BUTTON_ADD}',
	'buttonMoveAll'                     : '{L_AJAX_BUTTON_MOVE_ALL}',
	'parentBlock'                       : '{L_AJAX_PARENT_BLOCK}',
	'parentBlockNone'                   : '{L_AJAX_PARENT_BLOCK_NONE}',
	'confirmDelete'                     : '{L_AJAX_CONFIRM_DELETE}',
	'removedBlock'                      : '{L_AJAX_REMOVED_BLOCK}',
	'savingChanges'                     : '{L_AJAX_SAVING_CHANGES}',
	'savingChangesDone'                 : '{L_AJAX_SAVING_CHANGES_DONE}',
	'statusAdding'                      : '{L_AJAX_STATUS_ADDING}',
	'statusAddingError'                 : '{L_AJAX_STATUS_ADDING_ERROR}',
	'errorConnection'                   : '{L_AJAX_ERROR_CONNECTION}',
	'errorParser'                       : '{L_AJAX_ERROR_PARSER}',
	'manageBlocks'                      : '{L_AJAX_MANAGE_BLOCKS}',
	'moveAllSelect'                     : '{L_AJAX_MOVE_ALL_SELECT}',
	'selectType'                        : '{L_AJAX_SELECT_TYPE}',
	'blockType'                         : '{L_AJAX_BLOCK_TYPE}',
	'selectTypeFile'                    : '{L_AJAX_SELECT_TYPE_FILE}',
	'selectTypeHTML'                    : '{L_AJAX_SELECT_TYPE_HTML}',
	'selectTypeBBCode'                  : '{L_AJAX_SELECT_TYPE_BBCODE}',
	'blockContent'                      : '{L_AJAX_BLOCK_CONTENT}',
	'viewedBy'                          : '{L_AJAX_VIEWED_BY}',
	'userGroups'                        : '{L_AJAX_USERGROUPS}',
	'userGroupsAll'                     : '{L_AJAX_USERGROUPS_ALL}',
	'userGroupsEdit'                    : '{L_AJAX_USERGROUPS_EDIT}',
	'blockUsed'                         : '{L_AJAX_BLOCK_USED}',
	'blockUsedNone'                     : '{L_AJAX_BLOCK_USED_NONE}',
	'blockUsedDelete'                   : '{L_AJAX_BLOCK_USED_DELETE}',
	'blockUsedLayout'                   : '{L_AJAX_BLOCK_USED_LAYOUT}',
	'blockUsedLayoutSpecial'            : '{L_AJAX_BLOCK_USED_LAYOUT_SPECIAL}',
	'blockUsedLayoutGlobal'             : '{L_AJAX_BLOCK_USED_LAYOUT_GLOBAL}',
	'blockUsedClick'                    : '{L_AJAX_BLOCK_USED_CLICK}',
	'editBlockSettings'                 : '{L_AJAX_EDIT_BLOCK_SETTINGS}',
	'editBlockSettingsTip'              : '{L_AJAX_EDIT_BLOCK_SETTINGS_TIP}',
	'editBlockSettingsAlt'              : '{L_AJAX_EDIT_BLOCK_SETTINGS_ALT}',
	'blockNotFound'                     : '{L_AJAX_BLOCK_NOT_FOUND}'
};

// ]]>
</script>